# These settings are deployment specific and users can provide customizations
# Below is an example using speech service containers in containerpreview.azurecr.io

# speech-to-text configurations
# Refer to the charts/speechToText/values.yaml
speechToText:
  enabled: true
  image:
    registry: containerpreview.azurecr.io
    repository: microsoft/cognitive-services-speech-to-text
    tag: latest
    pullSecrets:
      - containerpreview
    args:
      eula: accept
      billing: https://fake.api.cognitive.microsoft.com
      apikey: dummy
