# These settings are deployment specific and users can provide customizations
# Below is an example using speech service containers in containerpreview.azurecr.io

# speech-to-text configurations
# Refer to the charts/speechToText/values.yaml
speechToText:
  enabled: true
  image:
    registry: containerpreview.azurecr.io
    repository: microsoft/cognitive-services-speech-to-text
    tag: latest
    pullSecrets:
      - containerpreview
    args:
      eula: accept
      billing: https://fake.api.cognitive.microsoft.com
      apikey: dummy
  service:
    annotations:
      test/annotation1: "test_value1"
      service.beta.kubernetes.io/azure-load-balancer-internal: true

# text-to-speech configurations
# Refer to the charts/textToSpeech/values.yaml
textToSpeech:
  enabled: true
  image:
    registry: containerpreview.azurecr.io
    repository: microsoft/cognitive-services-text-to-speech
    tag: latest
    pullSecrets:
      - containerpreview
    args:
      eula: accept
      billing: https://fake.api.cognitive.microsoft.com
      apikey: dummy
  service:
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: true
